apiVersion: v1
kind: Pod
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory

spec:
  containers:
  - name: ds
    imagePullPolicy: Always
    image: ghcr.io/retaildevcrews/ngsa-app:beta
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests: 
        memory: "256Mi"
        cpu: "250m"
    args:
      - --in-memory
      - --prometheus
      - --log-level
      - Warning
      - --request-log-level
      - Information
      - --zone
      - dev
      - --region
      - dev
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  labels:
    app: ngsa-memory
spec:
  type: NodePort
  selector:
    app: ngsa-memory
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
