apiVersion: v1
kind: Pod

metadata:
  name: webv
  labels:
    app: webv

spec:
  containers:
  - name: app

    image: ghcr.io/retaildevcrews/webvalidate:beta
    imagePullPolicy: Always

    args: 
    - --sleep
    - "1000"
    - --prometheus
    - --run-loop
    - --verbose
    - --log-format
    - Json
    - --server
    - http://ngsa-memory:8080
    - --files
    - benchmark.json
    - --zone
    - dev
    - --region
    - dev

---

apiVersion: v1
kind: Service
metadata:
  name: webv
  labels:
    app: webv
spec:
  type: NodePort
  selector:
    app: webv
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
